### ISSUE TITLE
Docker 破解 2020.2.5f1 失败

### ISSUE THREAD

**Issue by AlianBlank** [tylearymf/unihacker-docker#1]
![image](https://github.com/tylearymf/unihacker-docker/assets/1950044/428a0c0a-8c19-4658-9077-6205f071ac39)

**Comment by tylearymf** [comment]
看着像是逻辑出问题了，不过最近没空搞这个，周末我看看

**Comment by AlianBlank** [comment]
我已经追到了以下代码位置异常
UnityPatcher.cs->构造函数->代码段:
由于不知道内部破解原理逻辑.不知道如何修复
var darkIndexes = BoyerMooreSearcher.FindPattern(patchInfo.DarkPattern, fileBytes);
var lightIndexes = BoyerMooreSearcher.FindPattern(patchInfo.LightPattern, fileBytes);

以下附上调试信息图和数据:

![image](https://github.com/tylearymf/unihacker-docker/assets/1950044/1722332f-1a92-438c-b9b6-a8d7818117d2)

以下为控制台docker 输出:
![image](https://github.com/tylearymf/unihacker-docker/assets/1950044/ef28b225-3ab2-4330-b697-f9ccc8718687)
